package com.sohardh.x_post_hitl.service;

import com.sohardh.x_post_hitl.model.PostSession;
import com.sohardh.x_post_hitl.model.ScheduledPost;
import com.sohardh.x_post_hitl.repository.PostSessionRepository;
import com.sohardh.x_post_hitl.repository.ScheduledPostRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;

@Service
@RequiredArgsConstructor
@Slf4j
public class GenerationScheduler {

    private final XPromptEngine promptEngine;
    private final PostSessionRepository postSessionRepository;
    private final ScheduledPostRepository scheduledPostRepository;

    @Scheduled(cron = "0 0 8 * * ?", zone = "Asia/Calcutta")
    @Transactional
    public void generateDailyPosts() {
        log.info("Triggering daily post generation at 8 AM IST");
        
        List<String> postDrafts = promptEngine.generatePosts(5);
        
        if (postDrafts.isEmpty()) {
            log.warn("No posts generated by LLM.");
            return;
        }

        PostSession session = PostSession.builder()
                .createdAt(LocalDateTime.now())
                .isClosed(false)
                .build();
        
        session = postSessionRepository.save(session);

        for (int i = 0; i < postDrafts.size(); i++) {
            ScheduledPost post = ScheduledPost.builder()
                    .content(postDrafts.get(i))
                    .serialNumber(i + 1)
                    .status(ScheduledPost.PostStatus.DRAFT)
                    .session(session)
                    .build();
            scheduledPostRepository.save(post);
        }
        
        log.info("Successfully generated {} posts for session {}", postDrafts.size(), session.getId());
    }
}
