package com.sohardh.x_post_hitl.service;

import com.sohardh.x_post_hitl.model.PostSession;
import com.sohardh.x_post_hitl.model.ScheduledPost;
import com.sohardh.x_post_hitl.repository.PostSessionRepository;
import com.sohardh.x_post_hitl.repository.ScheduledPostRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
@Slf4j
public class PostSessionService {

  private final XPromptEngine promptEngine;
  private final PostSessionRepository postSessionRepository;
  private final ScheduledPostRepository scheduledPostRepository;

  @Transactional
  public String startNewSession(int count) {
    log.info("Starting new post session with {} initial posts", count);

    List<String> drafts = promptEngine.generatePosts(count);
    if (drafts.isEmpty()) {
      return "No posts were generated by the LLM. Please check topics and try again.";
    }

    PostSession session = PostSession.builder()
        .createdAt(LocalDateTime.now())
        .isClosed(false)
        .build();
    session = postSessionRepository.save(session);

    StringBuilder message = new StringBuilder();
    message.append("Daily Drafts (Session ").append(session.getId()).append(")\n\n");

    for (int i = 0; i < drafts.size(); i++) {
      ScheduledPost post = ScheduledPost.builder()
          .content(drafts.get(i))
          .serialNumber(i + 1)
          .status(ScheduledPost.PostStatus.DRAFT)
          .session(session)
          .build();
      scheduledPostRepository.save(post);
      message.append(i + 1).append(") ").append(drafts.get(i)).append("\n\n");
    }

    message.append("Reply 'more' for 2 additional drafts.\n");
    message.append("Or reply with CSV numbers to approve (e.g., 1,3). Others will be discarded.");

    return message.toString();
  }

  @Transactional
  public String addMoreDrafts(int count) {
    Optional<PostSession> activeSessionOpt = postSessionRepository.findFirstByIsClosedFalseOrderByCreatedAtDesc();
    if (activeSessionOpt.isEmpty()) {
      return "No active session found. Please wait for the daily batch or start one manually.";
    }

    PostSession session = activeSessionOpt.get();
    List<ScheduledPost> currentPosts = scheduledPostRepository.findBySession(session);
    int lastSerialNumber = currentPosts.stream()
        .mapToInt(ScheduledPost::getSerialNumber)
        .max()
        .orElse(0);

    List<String> moreDrafts = promptEngine.generatePosts(count);
    if (moreDrafts.isEmpty()) {
      return "No more posts were generated. Please try again later.";
    }

    StringBuilder message = new StringBuilder();
    message.append("Additional Drafts (Session ").append(session.getId()).append(")\n\n");

    for (int i = 0; i < moreDrafts.size(); i++) {
      int newSerialNumber = lastSerialNumber + i + 1;
      ScheduledPost post = ScheduledPost.builder()
          .content(moreDrafts.get(i))
          .serialNumber(newSerialNumber)
          .status(ScheduledPost.PostStatus.DRAFT)
          .session(session)
          .build();
      scheduledPostRepository.save(post);
      message.append(newSerialNumber).append(") ").append(moreDrafts.get(i)).append("\n\n");
    }

    return message.toString();
  }

  @Transactional
  public String approvePosts(String csvInput) {
    Optional<PostSession> activeSessionOpt = postSessionRepository.findFirstByIsClosedFalseOrderByCreatedAtDesc();
    if (activeSessionOpt.isEmpty()) {
      return "No active session found.";
    }

    PostSession session = activeSessionOpt.get();
    List<ScheduledPost> allPosts = scheduledPostRepository.findBySession(session);

    Set<Integer> approvedSerials;
    try {
      approvedSerials = Arrays.stream(csvInput.split(","))
          .map(String::trim)
          .filter(s -> !s.isEmpty())
          .map(Integer::parseInt)
          .collect(Collectors.toSet());
    } catch (NumberFormatException e) {
      return "Invalid input. Please provide comma-separated serial numbers (e.g., 1,3).";
    }

    if (approvedSerials.isEmpty()) {
      return "No valid serial numbers found in your reply.";
    }

    long approvedCount = 0;
    for (ScheduledPost post : allPosts) {
      if (approvedSerials.contains(post.getSerialNumber())) {
        post.setStatus(ScheduledPost.PostStatus.APPROVED);
        approvedCount++;
      } else {
        post.setStatus(ScheduledPost.PostStatus.DISCARDED);
      }
    }

    session.setClosed(true);
    postSessionRepository.save(session);
    scheduledPostRepository.saveAll(allPosts);

    return String.format(
        "Session %d closed. %d posts approved and scheduled for randomized publishing. Others discarded.",
        session.getId(), approvedCount);
  }
}
